# Site settings
title: Andrey Chernih
email: andrey.chernih@gmail.com
description: "Ruby on Rails, DevOps, Java and Android"
baseurl: ""
url: "http://andrey.chernih.me"
username: andreychernih
twitter_username: brainslug

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments
