# Site settings
title: Andrey Chernykh
email: andrey.chernih@gmail.com
description: "Software Engineering and things"
baseurl: ""
url: "https://andreychernih.github.io"
username: andreychernih
twitter_username: brainslug

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments
